"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.handlers = exports.groups = exports.Output = exports.MessageData = exports.CommandGroup = exports.Command = exports.Bot = void 0;
const objects_1 = require("./app/objects");
Object.defineProperty(exports, "Bot", { enumerable: true, get: function () { return objects_1.Bot; } });
Object.defineProperty(exports, "Command", { enumerable: true, get: function () { return objects_1.Command; } });
Object.defineProperty(exports, "CommandGroup", { enumerable: true, get: function () { return objects_1.CommandGroup; } });
Object.defineProperty(exports, "MessageData", { enumerable: true, get: function () { return objects_1.MessageData; } });
Object.defineProperty(exports, "Output", { enumerable: true, get: function () { return objects_1.Output; } });
const groups = require("./app/groups");
exports.groups = groups;
const handlers = require("./app/handlers");
exports.handlers = handlers;
